### ISSUE TITLE
fine-tuning config files and fine-tuned models

### ISSUE THREAD

**Issue by smao-astro** [camlab-ethz/poseidon#9]
Hi,

Thank you for publishing this fantastic project. May I ask if you could share 

1. the fine-tuning configuration used for the downstream tasks in the paper
2. the fine-tuned models mentioned in the paper?

Thanks,
Shunyuan

**Comment by maximilianherde** [comment]
Hi Shunyuan,

Are you referring to the yaml configuration? You can find all used parameters in the **appendix of our paper in section C.1**. From these, the yaml configuration can be easily built.
There are too many finetuned models to share them all -- we have 15 tasks, ran data size scaling for each task with 11 datapoints, and have three model sizes, which amounts to **495 finetuned models** (not counting any pretraining dataset ablations etc.). Easiest thing is to just finetune the model you want yourself (it is quite cheap and does not take long), otherwise I could send you a specific model.
